# Generated by Django 2.1.4 on 2018-12-18 21:51

from django.db import migrations, models
import django_ca.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0011_auto_20181208_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateauthority',
            name='private_key',
            field=models.FileField(default='', help_text='Path to the private key.', upload_to=django_ca.models.get_private_key_path),
            preserve_default=False,
        ),
    ]
