# Generated by Django 2.1.4 on 2018-12-18 21:37

import os

from django.core.files.base import ContentFile
from django.db import migrations


def copy_files(apps, schema_editor):
    CertificateAuthority = apps.get_model('django_ca', 'CertificateAuthority')
    for ca in CertificateAuthority.objects.filter(private_key=''):
        if not os.path.exists(ca.private_key_path):
            # Migration is run on machine that does not have the private keys locally
            continue

        with open(ca.private_key_path, 'r') as stream:
            raw_key = stream.read()

        name = ca.serial.replace(':', '')
        ca.private_key.save(name, ContentFile(raw_key))


def remove_files(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0012_certificateauthority_private_key'),
    ]

    operations = [
        migrations.RunPython(copy_files, remove_files),
    ]
